[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# SPA routing for Vite (prevents 404 on refresh)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
